name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: run release-please-action
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          path: api
